### ISSUE TITLE
Не преобразует путь модуля управляемого приложения

### ISSUE THREAD

**Issue by akademik1986** [SeiOkami/SonarBslFileNaming#12]
Не преобразует путь  модуля управляемого приложения
![image](https://github.com/SeiOkami/SonarBslFileNaming/assets/19662685/a80dc77d-d6a1-4bc6-8f9d-7fe5368a326b)

**Comment by alexandr-yang** [comment]
Какая версия сонара?

**Comment by akademik1986** [comment]
9.4
все никак не обновимся(
