### ISSUE TITLE
Не переименовываются объекты на вкладке Показатели

### ISSUE THREAD

**Issue by alei1180** [SeiOkami/SonarBslFileNaming#13]
Если перейти из страницы проекта в показатели дублирования, то там не происходит переименование путей

![image](https://github.com/SeiOkami/SonarBslFileNaming/assets/43796905/951b7e7d-4475-4060-873c-6954aa96d331)

![image](https://github.com/SeiOkami/SonarBslFileNaming/assets/43796905/338084b8-c1b9-4c1f-8f12-dbad884a9138)

Также не переименованые пути сохраняются и при вызове окна поиска файла где дублируется код
![image](https://github.com/SeiOkami/SonarBslFileNaming/assets/43796905/0b23664c-6281-42ef-9500-f42d7ea790c4)

Весрия соннар 10.3.0.82913

**Comment by alexandr-yang** [comment]
Основной список сделал, а с вьювером есть проблемы. Он как-то хитро переключается между контекстами, не получается отловить.

Еще есть тултип, в нем тоже наверное нужно наверное сделать преобразование.
<img width="238" alt="image" src="https://github.com/SeiOkami/SonarBslFileNaming/assets/1947592/2a3645e5-e960-4aff-82d9-6ed5420e50d9">

**Comment by alei1180** [comment]
> Основной список сделал, а с вьювером есть проблемы. Он как-то хитро переключается между контекстами, не получается отловить.
> 
> Еще есть тултип, в нем тоже наверное нужно наверное сделать преобразование. <img alt="image" width="238" src="https://private-user-images.githubusercontent.com/1947592/327550612-2a3645e5-e960-4aff-82d9-6ed5420e50d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MTIxNzcsIm5iZiI6MTcxNDcxMTg3NywicGF0aCI6Ii8xOTQ3NTkyLzMyNzU1MDYxMi0yYTM2NDVlNS1lOTYwLTRhZmYtODJkOS02ZWQ1NDIwZTUwZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMDQ1MTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2MzNGM4YzA5MjA0M2QyNDdmMzkzNWMxZDRiM2IwZjhlOWViZTc0Y2JmNzNkMWU4YzhmMDVhZDU1NzIxYTUwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.d41kE6maPwxJ9E9vkvfnbetF7iWCiA-TCI1R7_M1a2A">

Ждем реакции на ПР @SeiOkami

**Comment by alei1180** [comment]
> Основной список сделал

@alexandr-yang 
Проверил, с основным списком работает на вкладке показатели. Спасибо.
Предлагаю вторую часть по вьюверу вынести в отдельный issue а этот закрыть, после принятия @SeiOkami PR.

**Comment by SeiOkami** [comment]
Да, закроем этот issue, PR ещё пока в Draft'е

**Comment by alexandr-yang** [comment]
@SeiOkami можно мержить

**Comment by SeiOkami** [comment]
Коллеги, всем спасибо!
