### ISSUE TITLE
Не корректирует имя объекта метаданных внутри ошибки/дефекта

### ISSUE THREAD

**Issue by Kyrales** [SeiOkami/SonarBslFileNaming#7]
Не корректирует имя объекта метаданных внутри ошибки/дефекта, в случае если открыл дефект

**Comment by SeiOkami** [comment]
Исправлено
@Kyrales , спасибо за замечание

**Comment by Kholodarev** [comment]
У меня на версии v25.2.0.102705 аналогично - не корректирует имя объекта метаданных внутри ошибки/дефекта, в случае если открыл дефект
<img width="1078" height="655" alt="Image" src="https://github.com/user-attachments/assets/f48e9f3e-4e23-4961-99d7-9571ff945a3e" />
При этом в списке все корректно
<img width="1063" height="256" alt="Image" src="https://github.com/user-attachments/assets/720d1a54-f8a8-4704-afd3-a129c51f1b2b" />
