### ISSUE TITLE
Не изменяется отображение имен объектов метаданных

### ISSUE THREAD

**Issue by alexandr-yang** [SeiOkami/SonarBslFileNaming#9]
Нашел несколько мест, где есть проблемы с отображением метаданных

1. В списке Issues, при просмотре замечаний в левой панеле
```
<div class="concise-issue-component text-ellipsis note" title="src/AccumulationRegisters/ВзаиморасчетыСКонтрагентами/Ext/RecordSetModule.bsl">
    <bdi>src/AccumulationRegisters/ВзаиморасчетыСКонтрагентами/Ext/RecordSetModule.bsl</bdi>
</div>
```

2. В списке Security Hotspots в левой панеле
```
<div class="little-spacer-left hotspot-box-filename text-ellipsis" title="src/Catalogs/Партнеры/Ext/ObjectModule.bsl">
    <bdi>src/Catalogs/Партнеры/Ext/ObjectModule.bsl</bdi>
</div>
```

SonarQube Community Edition
Version 9.9.2 (build 77730)

**Comment by kuzyara** [comment]
Не понял как устанавливать, в итоге в тамперманки создал новый скрипт и скопировал туда из js-файла в репе.
![image](https://github.com/SeiOkami/SonarBslFileNaming/assets/2604430/20c7d03e-bb8b-4a7e-bea3-f6a474d72797)
а имена файлов как не работали так и не работают
![image](https://github.com/SeiOkami/SonarBslFileNaming/assets/2604430/c79f5364-eec7-4cfb-82a1-dedae12c77b0)

**Comment by alexandr-yang** [comment]
В шапке скрипта есть настройки, тебе нужно добавить туда свой свой сервер
`// @match http://sonar-server.rossko.local/*`

**Comment by kuzyara** [comment]
поменял, скрипт заработал, 
зашел в отладку, поставил точки останова на каждую функцию селектора - не срабатывает ни одна
![image](https://github.com/SeiOkami/SonarBslFileNaming/assets/2604430/59abdf30-0f5a-497b-a14b-eea54d57fe94)
